ProjectPythia/projectpythia.github.io

content/index.md

Turns out is wasn't the `image` directive, but a typo with the *case* of one letter in the NSF logo URL.  This fixes that (which doesn't display on my machine, annoyingly).

Bug fixes 2

---

.readthedocs.yaml

Towards fixing https://github.com/ProjectPythia/projectpythia.github.io/issues/16 by taking advantage of https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Enable documentation autobuilds on Readthedocs

---

CONTRIBUTING.md
README.md

As discussed in #9, this PR adds basic instructions to the README and the Contributor page for how to render the site locally.

Add build instructions

---

content/index.md
content/pages/meetings.md

Creating a draft PR to address #8.  We need to finalize a meeting schedule (day and time) and then I will:

Meeting Schedule & Notes Page

---

.github/CODEOWNERS

The GitHub usernames listed in this file will be triggered automatically for review.

Add first draft of CODEOWNERS file

---

content/index.md
content/pages/discussion.md

This is a draft to add a link to the new GitHub Discussions page on the Portal.  Let me know what you think!

Add link to GitHub Discussions on Portal

---

content/pages/meetings.md

I have unified the two WG notes documents into 1 Google Doc, and I have updated the Pythia Google Calendar events, too.
Closes #42.

Update meeting notes link

---

content/_templates/layout.html

This adds the necessary javascript to the head section of the Sphinx theme template to enable Google Analytics tracking.

Attempt to add Google Analytics to portal

---

ci/environment.yml

Fixes #68 
This just makes our `ci/environment.yml` file (used by conda to make the build environment when building the site locally) consistent with `requirements.txt` (used by pip to make the build environment on readthedocs)
It would be better to avoid duplicating the build requirements. I'll open a separate issue about that.

Make environment.yml consistent with requirements.txt

---

content/conf.py

This PR addresses the warnings  the user would get when building html 
```bash 
WARNING: config `myst_admonition_enable` is deprecated, please add "colon_fence" to `myst_enable_extensions = []` WARNING: config `myst_deflist_enable` is deprecated, please add "deflist" to `myst_enable_extensions = []`
```

Fix deprecated myst config

---

.github/ISSUE_TEMPLATE/update-external-links-gallery.md
.github/workflows/collect-user-submission.py
.github/workflows/update-external-links-gallery.yaml
setup.cfg

This is my attempt at addressing #80. This PR consists of an issue template and a GitHub workflow that will operate as follows:
- A user opens a new issue using the template included in this PR
<details
</details>
<details>
</details>
- Here's what the filled out issue template looks like: 
- Once the issue is created, GitHub triggers the workflow. The workflow does a few things
- (1) Lets the user know that we are running some validation checks
- (2) Runs the validation checks
- (3) Once the validation checks are passing, the Github workflow opens a PR on behalf of the user
- (4) Once the PR is opened, we post a reply to the original issue to let the user know that we opened a PR on their behalf
<details>
</details>
<details>
</details>
- The workflow is designed to be triggered when the …

Add GH workflow for updating external links gallery via issue template

---

.github/workflows/update-external-links-gallery.yaml

This disables `pre-commit` hooks until we have a workflow for running `pre-commit` checks as part of the CI.

Disable pre-commit hooks for the time being

---

content/_ext/yaml_gallery_generator.py

This PR adds support for an arbitrary number of authors. Previously, the gallery generator supported no more than 2 authors. This assumptions resulted in `UnboundLocalError: local variable 'authors_str' referenced before assignment error` error. See https://readthedocs.org/projects/projectpythia/builds/13991093/. This fixes the build for https://github.com/ProjectPythia/projectpythia.github.io/pull/92.

External links gallery: add support for an arbitrary number of authors

---

README.md
content/pages/contributing.md

A few minor corrections to the contributor's guide.

Minor revisions to contributor's guide

---

CONTRIBUTING.md
ci/environment.yml

Closes #122 
- Add `pre-commit` to the `pythia` environment in `ci/environment.yml`
- Update instructions to use `conda env update` rather than `conda env create`

Add pre-commit to environment

---

.github/workflows/ci.yaml
.github/workflows/preview.yaml

Towards #157. 
_Note_: 
1. Changes in this PR will take effect once this PR is merged
2. Readthedocs previews should be disabled once we have confirmation that GitHub Actions + Netlify are working properly

Preview PRs via Netlify + GitHub Actions

---

portal/contributing.md
portal/foundations.md
portal/gallery.yaml
portal/index.md

Addresses https://github.com/ProjectPythia/pythia-foundations/issues/176 by referring to the book consistently as "Pythia Foundations" rather than "Project Pythia Foundations".

Use Pythia Foundations as the book title consistently

---

portal/_static/custom.css
portal/_static/images/logos/pythia_logo-blue-rtext.svg
portal/about.md
portal/conf.py
portal/index.md

Addresses #116 
Also addresses #214 by explicitly mentioning Pangeo in the the landing section.

Improve portal landing page and About content

---

portal/index.md

Fixed #222 - Highlighting all of the Pythia resources from the landing page
This PR addresses the content aspect of #222, adding descriptions and links for webinars, data sets, and cookbooks.
It does not address the aesthetics issues raised by @brian-rose, namely:
"Get rid of text and present a grid/panels of resources; more graphical and inviting"
I suggest we consider opening a second issue to address the aesthetics.

Addresses #222 - Highlighting all of the Pythia resources from the landing page

---

portal/cookbooks.md
portal/index.md

Related to #240, this PR creates a placeholder landing page for the eventual Cookbooks gallery, puts a link to @mgrover1's Radar Cookbook on the landing page, and links to this landing page from the Cookbooks button on the main landing page.
This PR does not change the top navbar.

Make a placeholder Cookbooks landing page and link to it

---

portal/_extensions/cookbook_gallery_generator.py
portal/_extensions/resource_gallery_generator.py

The gallery titles are too long. The "Pythia Cookbooks Gallery" title takes up too lines with the current CSS. The fastest fix is to remove the word "Pythia" from the title. 
Further CSS revisions for different screen sizes in another PR.
See discussion in #256

Remove "Pythia" from gallery titles

---

portal/index.md

Change gh discussions to pangeo discourse on portal index

---

portal/contributing.md

It took me a minute to find the appropriate place to ask https://discourse.pangeo.io/t/questions-about-pythia-cookbooks/3021/2 based on the conversations in https://github.com/ProjectPythia/projectpythia.github.io/discussions, updating this link based on my interpretation so it will hopefully be quicker for others.

Provide link to Pangeo Discourse category

---

README.md

With #310 we now have a nightly build for this repo.
This PR adds a status badge for that nightly build, and removes the broken old badge.

Add nightly-build status badge to README

---

.pre-commit-config.yaml

As noted in #307 , pre-commit was failing with an unhelpful message, **_The Poetry configuration is invalid_**. Updating `.pre-commit-config.yaml` so that the latest (5.12.0) version of `isort` is used looks to be the key fix here (see #312), but I also eliminated what seems to be unnecessary pinned versions of `nbqa-black` and `nbqa-pyupgrade` hooks in `nbqa`, and also eliminated the now-deprecated `seed-isort-config` repo.

Remove pinned versions in .pre-commit-config.yaml / update isort

---

portal/index.md

This PR adds a link to the event on the main portal page. Perhaps we want to link this differently, but this was the easiest solution I found.
Eventually we may want an "events" tab in the nav bar that lists past events, events we'll be present at or give talks/tutorials, and events that we host.

add link to event page from portal

---

portal/resource_gallery.yaml

Within the Xarray tutorial is a great Dask notebook https://tutorial.xarray.dev/intermediate/xarray_and_dask.html so I wanted to add the dask package tag to the Xarray tutorial card.

add dask tag to xarray tutorial

---

portal/index.md

Remove Hackathon banner now that event has ended. We can use this space for the post-survey or a SciPy ad if we need, but I'm glad to say goodbye to it for now. Reverts #328.

Remove hackathon banner

---

CONTRIBUTING.md

Sphinx ABlog instructions in Contributing Guide

add blog instructions

---

.github/workflows/collect-user-submission.py
portal/index.md

Closes #369.
Move `IssueInfo.data` initialization from `__post_init_post_parse__()` to `_… get_input_()` as `__post_init_post_parse__()` has been [removed from the API with Pydantic V2](https://docs.pydantic.dev/latest/migration/#changes-to-dataclasses).

Fix the broken resource gallery submission validation

---

.github/workflows/collect-user-submission.py
.github/workflows/update-resource-gallery.yaml

Revert namely the commits 876f5b2, 0b23322, e365d58, 1cf502a that were pushed in PRs from 376 through 379. Even though the changes were in the direction to fixing the things, I am reverting these because I had bypassed branch protection rules to get the Resource Gallery Submission workflow issues fixed but couldn't succeed yet. 
I am going to make all these changes in a PR and ask reviews.

Revert changes made in PRs from 376 to 379

---

.github/workflows/collect-user-submission.py
portal/_extensions/gallery_generator.py
portal/resource_gallery.yaml

Closes #369 
This PR addresses the needs due to version changes in pydantic as suggested in the [pydantic Migration Guide](https://docs.pydantic.dev/2.5/migration/):
- Remove the deprecated `__post_init_post_parse__()` and move its functionality into `_get_inputs()`
- Use `model_dump_json()` instead of deprecated `dict()`
- Also uses "affiliation" instead of formerly used "institution" in `gallery_generator.py`, `resource_gallery.yaml`, and `collect-user-submission.py` files. This change also needed the [ProjectPythia/.github/PR#63](https://github.com/ProjectPythia/.github/pull/63)
Note to reviewers: [See](https://github.com/ProjectPythia/projectpythia.github.io/pull/381#issuecomment-1869774705)

Fix resource gallery submission workflow

---

portal/index.md

Closes #349 
The places that were pointed out in the issue 349 (i.e. "The Project Team" in the page footer and in the [Who is Project Pythia section](https://projectpythia.org/about.html#who-is-project-pythia) of the About page) have already been accidentally merged via this [commit](https://github.com/ProjectPythia/projectpythia.github.io/commit/161e6918fc2dbc78aa3f5bd1dab36e02ee42e56a) last week.
This PR additionally fixed a link in the "Join us!" part in index.md. Additional search for the "team" did not return any links to the formerly removed team part in index.md.
So, all changes that need to be done for the team links should be done now.

Address #349: Fix broken links to the Pythia team in a few places

---

portal/index.md
portal/posts/cookoff2024-website.md

Following the same button format we used last year, and adding a blog post. Both link to the new [Cook-off 2024 site](https://projectpythia.org/pythia-cookoff-2024/)

Add Cookoff 2024 event link and blog post

---

portal/index.md

Update the description of our meeting calendar and links to agenda documents. Remove references to explicit times/dates and the old "weekly working group" meetings.

Update meeting information

---

.github/workflows/get-metrics.py
CONTRIBUTING.md

Related to #319 (won't close automatically, want to ensure the actions are all running smoothly after merge first).
Response to #413 
GH secrets treat new lines differently than the Google Analytics API key expects. Essentially '\\' is an escape character, so sometimes during the encryption and getting of the secret, GitHub escapes the new line and causes issues. For some reason GH secrets when returned can give '\\\n' where you'd expect '\n'.
Without printing the secret to ensure that this is the issue, I was able to confirm that the discrepancy in secret length aligns with extra '\\'s. This PR will find any '\\\n's and replace them with '\n'.
Maybe this was common knowledge, but I am amused that in this comment I have to add an extra '\\' everywhere for it to show up as intended in the …

String manipulation on GH secret in metrics automation AND contributor's instructions

---

environment.yml
portal/_extensions/gallery_generator.py
portal/_static/custom.css
portal/conf.py

This replicates the look of the old gallery pretty closely with cards instead of panels. 
The "...more" button pop-ups do NOT work here

Similar gallery generation for try_updated_theme

---

portal/cookbook-guide.md

This PR just replaces a bare URL with a proper link so it renders correctly on the portal site. We want people to be able to find the Template repo!

Fix link to Cookbook Template repo

---

portal/resource_gallery.yaml

Here's a manual PR to address #397

Add Herbie documentation to gallery

---

.github/workflows/update-resource-gallery.yaml
portal/resource_gallery.yaml

Update resource_gallery.yaml to add UXarray

---

.github/workflows/publish-site.yaml

In an attempt to fix the Issue #457, remove `build_from_code_artifact: 'true'` from `build` job of the publish-site.yaml. 
EDIT 2024-9-17: Never mind the above description; we revert those changes. Instead, add `include-hidden-files` into upload-artifact re this [release note](https://github.com/actions/upload-artifact/releases/tag/v4.4.0) per @brian-rose 's [comment](https://github.com/ProjectPythia/projectpythia.github.io/issues/457#issuecomment-2356706620).

Fix publish-site.yaml 

---

.github/workflows/sphinx-link-checker.yaml

Related to https://github.com/ProjectPythia/cookbook-actions/pull/124. This PR replaces Mambaforge with Miniforge in the custom link-checker workflow housed in this repo.

Switch link checker workflow to miniforge

---

.github/workflows/publish-site.yaml
.github/workflows/trigger-preview.yaml

Same as https://github.com/ProjectPythia/pythia-foundations/pull/496
This needs doing for consistency with https://github.com/ProjectPythia/cookbook-actions/pull/135
The preview will fail here, that is expected.

Remove cname input to deploy-book workflow

---

portal/_static/custom.css

For dark mode users, the text on the current Project Pythia homepage is barely readable because of black font color.
The fix in this PR adapts the colors for dark mode to solve these issue, see screenshot below.
The other changes in this PR where automatically added, I assume because of the pre-commit hooks?

Fix css for dark mode

---

portal/index.md

Our BinderHub resources have successfully migrated to our new ACCESS allocation so we can remove the Dec. 23 maintenance alert.

Remove Dec. 23 JS2 Maintenance alert

---

CODEOFCONDUCT.md

Created in order to provide the community with a clear email etc. to report any unacceptable instances in the Code of Conduct. We are now adding the ProjectPythia/core Github team and the Pythia's email alias into the CoC to address this.
The updated text is adapted from the [Contributor Covenant Code of Conduct, version 2.1](https://www.contributor-covenant.org/), [version 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html)

Update CODEOFCONDUCT.md to provide a clear way of reporting instances to the Pythia community leaders

---

portal/index.md

The latest binder hub maintenance banner inadvertently broke the banner about new Cookbooks.
I think we are done with BinderHub maintenance so I'm removing that banner and fixing the other one.
In general I suggest we leave the blog posts themselves intact, so I'm not touching that part.

Remove maintenance banner; fix cookbook banner

---

.github/workflows/nightly-build.yaml
.github/workflows/publish-site.yaml
.github/workflows/trigger-link-check.yaml
environment.yml
portal/index.md
requirements.txt

Closes #521 
~~Seeing if including Jupyterlab in the environment file resolves the build-time failure of the metrics script.~~
This PR attempts to fix the broken metrics script. Two key changes:
- include all the necessary packages for the python metrics script in the `environment.yml`
- Modify the workflow calls to pass the necessary Google Analytics secrets to the `build-book.yml` workflow where myst build is called.
Limitation (discussed inline below): Can't pass the secrets for Pull Requests that originate from other forks. So metrics won't build in the previews. Including this preview.

Get metrics working

---

portal/posts/binderhub_status.md
portal/posts/cookoff2023.md
portal/posts/cookoff2024-savethedate.md
portal/posts/cookoff2024-website.md
portal/posts/cookoff2025-website.md
portal/posts/fundraiser.md
portal/posts/new-cookbooks.md

> [!Important]
> Depends upon https://github.com/ProjectPythia/pythia-config/pull/12
This PR uses GitHub IDs for blog post authors, which are mapped to contributor details in the upstream `pythia.yml`.

feat: use upstream config for contributors

---

portal/src/blogpost.py

This PR puts in a more stringent glob path to look for blog posts. I encountered issues when building the site locally with stray extra posts showing up on the rendered page that were found in the `_build` directory.

Restrict blog post list path
