- ci/environment.yml
> Add pandas to conda environment

- content/conf.py
- content/index.md
- content/pages/about.md
Just a few simple tweaks to the layout and content.  Nothing much.
> Some tweaks to the site content

- CODEOFCONDUCT.md
- content/index.md
- content/pages/contributors.md
Addresses #4 
This is mostly just placeholder text but contains links to the source repo and the Code of Conduct.
> First draft of Contributors Guide

- content/pages/people.md
This PR implements @erogluorhan's suggestions post-merge in #10.
> Orhan's recommendations

- content/pages/links.md
I have reworked the links document a bit:
1. Added several packages with links to tutorials, galleries, and videos if available
2. Moved a few of the items in the Introductory/Basics section to the Packages section.
3. Added several courses/multi-lesson tutorials to the Lessons and Courses section.
This is just a starting point in terms of content for these sections; just wanted to get some feedback first before proceeding.
One challenge I see is to keep this document from getting too large and unwieldy.
> Reworked links.md page

- .github/CODEOWNERS
Added @ktyle to the CODEOWNERS/content section
> Add @ktyle to /content/ section in CODEOWNERS

- content/pages/people.md
I added myself onto the project members page.
> Add name to pages

- README.md
Addresses #63 by adding a link to the rendered Contributor's Guide to the repo's README.
> Add link to Contributors Guide to README

- .github/workflows/linting.yaml
- .github/workflows/update-external-links-gallery.yaml
- .gitignore
This is a follow-up for #91 and #93
> Re-enable pre-commit hooks

- content/_ext/yaml_gallery_generator.py
Addresses https://github.com/ProjectPythia/projectpythia.github.io/pull/107#issuecomment-860978039
- Closes #108
> Fix bug that breaks gallery filters

- content/links.yaml
Just adding some more tags to an existing link in the Links Gallery
> Add more useful tags for The Climate Laboratory

- portal/_templates/layout.html
> Add Google Analytics block back to landing page

- portal/_extensions/yaml_gallery_generator.py
- portal/_static/custom.css
I've made some CSS tweaks to the portal to improve it's look and operation on small screens.
closes #121
> Fix gallery and modals for better viewing on small screens

- CONTRIBUTING.md
> Remove obsolete references to content directory

- CONTRIBUTING.md
Along with https://github.com/ProjectPythia/pythia-foundations/pull/148, this PR finishes addressing https://github.com/ProjectPythia/projectpythia.github.io/issues/162 by adding detail to the portal CONTRIBUTING.md on how to keep your conda environment up to date.
> Update conda docs

- portal/_extensions/yaml_gallery_generator.py
> Fix glitch with multi-word tags in filtering

- portal/gallery.yaml
> Add tutorial tag to tutorial videos

- portal/gallery.yaml
> rm video tag to "your first" site

- portal/conf.py
Adding link to YouTube channel to Portal navbar.
> add YouTube navbar link

- portal/_extensions/truncatehtml.py
- portal/gallery.yaml
Add a check if an "&" is an `&` vs an HTML `&amp;`
> Fix edge case with & Token

- portal/index.md
> update Anderson's affiliation to carbonplan

- portal/index.md
Closes #253 
Does this look good @mgrover1 ?
> Change Max's affiliation to Argonne

- portal/contributing.md
> Fixed #261 - Added cookbooks to our contributor's guide

- portal/contributing.md
> Update link to Cookbook Contributor's Guide

- portal/index.md
Forgot one cookbook link that is now broken
> fix cookbook link

- portal/index.md
Update affiliation from NCAR to NVIDIA. Good luck @kmpaul at this next journey!
> update @kmpaul's affiliation

- portal/index.md
Noticed that the text still says we meet on Thursdays!
> fix meeting day in text

- .github/workflows/collect-user-submission.py
Make consistent with #246, should revive our submission generation action.
> Fix parsed submission yaml filename

- portal/resource_gallery.yaml
> Add Environmental Data Science Book to Gallery

- portal/contributing.md
> Update cookbook links in contributing.md

- .github/workflows/publish-site.yaml
- .github/workflows/trigger-preview.yaml
> Use the new publish_dir option for deploy-book workflow

- portal/conf.py
- portal/index.md
Some testing related to https://github.com/ProjectPythia/cookbook-actions/issues/60
This is expected to fail the link checker at first since it's a DOI for an AGU publication.
> Test of a DOI link

- portal/index.md
> Update index.md affiliations

- portal/about.md
Added the talks I could track down. See #348. Please add more talks too!
> add some talks

- portal/posts/cookoff2024-savethedate.md
Add save-the-date blog for 2024 cookoff
> Cookoff2024 savethedate

- CONTRIBUTING.md
Fixes this broken link: [Pythia Contributor's Guide](https://projectpythia.org/pages/contributing.html)
> Fix broken link in CONTRIBUTING.md.

- portal/about.md
Adding some recent talks as requested in #348
> Add BR talks to about page

- portal/about.md
Addresses part of #348 for SciPy 2022 and 2023 talks
> Add SciPy talks to about.md

- portal/about.md
Two talks added, mine and @jukent's.
> Add AGU talks to the About page

- portal/index.md
- portal/posts/cookoff2024-savethedate.md
- portal/posts/cookoff2024-website.md
We have mixed dates listed across sites. The official dates are Tues 11 Jun 2024 -- Fri 14 Jun 2024!
> Fix hackathon dates

- portal/about.md
Add links to AMS and Ocean Sciences talks to About page.
Toward closing #348
> Add two recent BR talks

- portal/about.md
Addresses #348 (thanks for the ping!)
> Add Camron AMS 2024 presentation

- .github/workflows/get-metrics.py
- .github/workflows/write-metrics-md.py
Adds a try-except block to help debug if github secret isn't being accessed or is malformed
Adds comments and docstrings throughout.
Still need to update contributing guide.
> Add comments to metrics code and add error handling

- portal/_extensions/gallery_generator.py
This PR fixes the same issue as https://github.com/ProjectPythia/cookbook-gallery/pull/204
We have the same code in both repos, same bug.
Closes #432
> Fix duplicate gallery cards

- portal/_extensions/gallery_generator.py
- portal/cookbook-guide.md
This PR get the Cookbook guide up to date and adds substantial detail on working with the Pythia infrastructure.
Closes #433
> Substantial rewrite of the Cookbook guide

- portal/index.md
> Remove hackathon banner

- .pre-commit-config.yaml
- portal/index.md
- portal/posts/fundraiser.md
Draft PR to demonstrate embedding fundraising on the site.
We can have more conversations about the text or where it should go. Personally, I like the way the UCAR page has the Donate button prominently next to the text (instead of hidden at the bottom) and the donate form is a pop up modal. This just a proof of concept.
> add fundraising

- portal/resource_gallery.yaml
> add geocat applications to resource gallery

- portal/resource_gallery.yaml
- Fix the thumbnail of PO.DAAC
- Revise the authors of UXarray
> Update two entries in resource_gallery.yaml

- portal/about.md
Just keeping this list of presentation about Pythia up to date.
> Add pangeo showcase talk to list of presentations

- portal/index.md
> Remove Jan. 6-9 Maintenance alert

- portal/index.md
> Sticky save the date to portal

- portal/posts/new-cookbooks.md
This PR will get the link checker passing again.
> Fix CESM LME link

- portal/posts/cookoff2025-website.md
Update Feb 20 blog post to reflect that registration is now open
> Change save-the-date to registration-is-open

- .github/workflows/nightly-build.yaml
- .github/workflows/publish-site.yaml
- environment.yml
Another attempt to resolve #521
> Fix secrets syntax

- portal/myst.yml
> Add analytics back!
